### ISSUE TITLE
Example, icon undefined

### ISSUE THREAD

**Issue by kirkins** [mattiaerre/react-open-weather-map#3]
I cloned this and then ran

    npm i
    npm run example

When I went to port 3000 in browser I got back

> TypeError: Cannot read property 'icon' of undefined

**Comment by kirkins** [comment]
I made the following changes to make the example work:

https://github.com/kirkins/react-open-weather-map/commit/b428f51f2516f912bc03997d549d05c6f53c712c

But it might be that the sample data was wrong(?)

**Comment by kirkins** [comment]
Above change was pointless. Only problem was sample data was different from that returned by API (which works fine with component).

**Comment by mattiaerre** [comment]
closing thanks to #4
